---
title: "Write like nobody's reading?"
format: revealjs
editor: 
  markdown: 
    wrap: 72
---

# Kia ora!

-   Check spelling and order of greetings, did from memory\*

Tēna tatou katoa \
Ko Uropi me Kanata te whakapaparangamai (spell check) (engari)

Ko Te Awamutu te whenua tupu

Ko Ō-Tawhao te marae

Ko Waitematā te kainga

Ko Liza taku ingoa

Tēna koutou katoa

# Who am I?

*Pull in CV at glance and add awards from UofT and UoA?*

# Get these slides

*TO DO*

*- Push to GitHub and get link*

*- QR code for slides*

*- link.lizabolton.com for these slides and other links for today's
session*

# Warm-up question

::: callout-note
**How do you think students view writing in your discipline?**
:::

### THINK. \[30 secs\]

Consider your answer to this question.

### PAIR. \[2 mins\]

Talk to the person next you about

-   What discipline do you/will you teach in?

*Insert the QR code (can reuse from Data Aotearoa)*

# Why write?

::: incremental
-   Communication with others

-   Processing and organising information (communicating with yourself)

-   Because \_\_\_\_\_\_\_\_ said you have to (lecturer, boss, journal
    publisher, grant authority...etc.)
:::

# What is low stakes writing?

Low stakes writing is writing where students do not need to feel a lot
of pressure about writing --- it is usually 'low stakes' in that it
isn't worth a lot of **marks,** but there are also **reputational
risks** that students perceive when others will be reading their
writing.

-   Opportunities for anonymous writing in class

    -   Risks of bad behaviour, but these are fairly easy to mitigate
        'live' and also not very common in my experience --- and I've
        taught large first year courses!

-   Opportunities for writing in assessments

# \[Find te reo name\] graduate profile activity

https://www.auckland.ac.nz/en/students/forms-policies-and-guidelines/student-policies-and-guidelines/graduate-profile.html

# Perfect is the enemy of good

Make the grading scheme clear to students.

# An example from my teaching

Context: First assignment in a stage 3 statistics paper (STATS 369: Data Science Practice)

2 of 20 marks

Read over the [current graduate capability themes, LEVEL 2: Graduate Capabilities -- Themes](https://www.auckland.ac.nz/en/students/forms-policies-and-guidelines/student-policies-and-guidelines/graduate-profile.html) or the refreshed version that connects to [Taumata Teitei](https://www.auckland.ac.nz/en/on-campus/life-on-campus/latest-student-news/curriculum-framework-transformation-programme0/university-graduate&~_). Choose one specific task or subtask in this assignment or in lab 01 or lab 02 and discuss how your work demonstrates ONE of these specific capabilities. Make sure you explain the capability in your own words as well as referencing the graduate profile. Assume your audience is the HR team at a potential employer for the Data Science job of your dreams. Write \~100 to 300 words. [2 marks]
